#!/bin/bash
set -eo pipefail

if [ ! -x "$(command -v stow)" ] ; then
  echo 'You must install stow to use this'
  exit
fi

if [ ! -x "$(command -v antibody)" ] ; then
  echo 'You must install antibody to use this'
  exit
fi

if [ ! -d "$HOME/bin" ] ; then
  echo "Creating $HOME/bin directory"
fi

stow -v -t ~ --dotfiles git tmux vim zsh

if [ ! -f "$HOME/.zsh_plugins.sh" ] ; then
  antibody bundle < ~/.zsh_plugins > ~/.zsh_plugins.sh
else
  echo "$HOME/.zsh_plugins.sh already exists, will not overwrite"
fi

if [ ! -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ] ; then
  curl -L -o ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim +PlugInstall +qa
else
  echo "vim-plug already installed"
fi
