#!/bin/zsh
set -eo pipefail

if [ ! -x "$(command -v stow)" ] ; then
  echo 'You must install stow to use this'
  exit
fi

if [ ! -d "$HOME/bin" ] ; then
  echo "Creating $HOME/bin directory"
  mkdir -p "$HOME/bin"
fi

if [ ! -d "$HOME/.config/alacritty" ] ; then
  echo "Creating $HOME/.config/alacritty directory"
  mkdir -p "$HOME/.config/alacritty"
fi

stow -v -t ~ --dotfiles git tmux vim zsh
stow -v -t ~/bin bin
stow -v -t ~/.config/alacritty alacritty
stow -v -t ~/.config/nvim nvim
stow -v -t ~/.config/zsh_plugins zsh_plugins
