# vim: set ft=tmux:
set -g mouse on
set-window-option -g mode-keys vi

# Better vim mode
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

bind-key h split-window -h
bind-key v split-window -v

set -g set-clipboard on

# Display options
set-option -g status-left-length 60

set -g set-titles off
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1

set -g monitor-activity on
set -g visual-activity on


# General compatibility settings
set-option -sg escape-time 10
set-option -g focus-events on
set-option -g default-terminal "screen-256color"
set-option -a terminal-features 'xterm-256color:RGB'

set -g @basebg '#15a395'
set -g @basefg 'black'
set-option -g status-style bg="#{@basebg}",fg="#{@basefg}"
set-option -g status-left " #{host} "
set-window-option -g window-status-format "[#I] #W "
set-window-option -g window-status-current-format "#[bg=#{@basefg},fg=#{@basebg}] [#I] #W #[bg=#{@basebg},fg=#{@basefg}]"
set-option -g status-right " %H:%M "
